config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}


  get '/me/articles', to: 'users#articles'
  get '/search', to: 'home#search'
  get '/find', to: 'home#find'
  get '/@:user', to: 'users#profile'
  get '/articles/search', to: "articles#image"
  get '/articles/:id/content', to: 'articles#content'
  
  resources :articles do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  before_create :set_defaults

  def set_defaults
    self.draft = true
    self.title = "Default Title"
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    '/'
  end

  protected

  def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end

end

app/controllers/articles_controller.rb
# frozen_string_literal: true
require 'json'
require 'unsplash'

class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @publishable = true

  end

  def create
    @article = current_user.articles.create(article_params)
    @article.save

    render json: { id: @article.id }
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      render json: { status: 1 }
    else
      render json: { status: 0 }
    end
end

  def edit


    @publishable = true
    @article = Article.find(params[:id])
    if(@article.user_id != current_user.id)
        redirect_to root
    end
  end

  def show
  end

  def content
    @article = Article.find(params[:id])

    render json: { content: @article.content }
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy

    render json: { status: 1 }
  end

  def show
    @article = Article.find(params[:id])

    if(@article.draft)
      redirect_to root
    end
      
  end

  def image
    q = params['q']
    page = params['page'] || 1

    search_results = Unsplash::Photo.search(q, page, 30)

    search_results.map! { |obj| obj.as_json['attributes']['table']}

    render json: { results: search_results }

  end

  private

  def article_params
    params.require(:article).permit(:content, :title, :subtitle, :tags, :display_image, :draft)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_commentable, only: :create
    
    
        def create
          params = comment_params
          params = params.merge(user_id: current_user.id)
          @commentable.comments.build(params)
          @commentable.save
          redirect_back(fallback_location: root_path)
        end

        def update
          puts params
          comment = Comment.find(params[:id])
          comment.update(content: params[:comment][:content])

          redirect_back(fallback_location: root_path)
        end

        def destroy
          comment = Comment.find(params[:id])
          comment.destroy

          render json: { status: 1 }
        end
    
        private
    
        def comment_params
          params.require(:comment).permit(:content)
        end
    
        def find_commentable
          if params[:comment_id]
            @commentable = Comment.find_by_id(params[:comment_id]) 
          elsif params[:article_id]
            @commentable = Article.find_by_id(params[:article_id])
          end
        end
    
    end
    

app/controllers/home_controller.rb
require 'fuzzy_match'

class HomeController < ApplicationController

  def index
    @articles = Article.where("draft = ?", false).to_a
    @intro = @articles.shift
  end

  def search
    if params[:q]
      fz = FuzzyMatch.new(Article.all, :read => :title)
      @articles = fz.find_all(params[:q])
    else
      @articles = Article.all
    end
  end


end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:profile, :articles]

  def articles
    @articles = current_user.articles
  end

  def profile
    @user = User.find_by username: params[:user]
    render 'profile'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def custom_flash
    flash_messages = []
    flash.each do |type, message|
        type = 'success' if type == 'notice'
        type = 'error'   if type == 'alert'
        text = "<script>toastr.#{type}('#{message}');</script>"
        flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="scroll-wrapper">

    <%= render "partials/navbar" %>

    <div class="wrapper">
        <div id="toolbar">
            <button class="ql-bold toolbar-option">
                <i class="material-icons"> format_bold </i>
            </button>
            <button class="ql-underline toolbar-option">
                <i class="material-icons"> format_underline </i>
            </button>
            <button class="ql-italic toolbar-option">
                <i class="material-icons"> format_italic </i>
            </button>
            <button class="ql-strike toolbar-option">
                <i class="material-icons"> strikethrough_s </i>
            </button>
            <button class="unsplash-image toolbar-option">
                <i class="material-icons"> add_photo_alternate </i>
            </button>
            <button class="ql-header toolbar-option" value="1" type="button">
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="#000000" d="M3,4H5V10H9V4H11V18H9V12H5V18H3V4M14,18V16H16V6.31L13.5,7.75V5.44L16,4H18V16H20V18H14Z" />
                </svg>
            </button>
            <button class="ql-header toolbar-option" value="2" type="button">
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="#000000" d="M3,4H5V10H9V4H11V18H9V12H5V18H3V4M21,18H15A2,2 0 0,1 13,16C13,15.47 13.2,15 13.54,14.64L18.41,9.41C18.78,9.05 19,8.55 19,8A2,2 0 0,0 17,6A2,2 0 0,0 15,8H13A4,4 0 0,1 17,4A4,4 0 0,1 21,8C21,9.1 20.55,10.1 19.83,10.83L15,16H21V18Z" />
                </svg>
            </button>
            
            <span class="save"></span>
        </div>

        <div id="editor">
        </div>
    </div>
</div>

<div class="image-wrapper">
    <div class="image-close">
        Cancel
    </div>

    <div class="image-content">
        <div class="image-search">
            <form id="unsplash-search">
                <input class="image-search-input" placeholder="Search for images...">
            </form>
        </div>
        <div class="image-results">
            
        </div>
    </div>
</div>

<%= javascript_include_tag 'write' %>
<%= javascript_include_tag 'edit' %>

app/views/articles/new.html.erb
<div class="scroll-wrapper">

    <%= render "partials/navbar" %>

    <div class="wrapper">
        <div id="toolbar">
            <button class="ql-bold toolbar-option">
                <i class="material-icons"> format_bold </i>
            </button>
            <button class="ql-underline toolbar-option">
                <i class="material-icons"> format_underline </i>
            </button>
            <button class="ql-italic toolbar-option">
                <i class="material-icons"> format_italic </i>
            </button>
            <button class="ql-strike toolbar-option">
                <i class="material-icons"> strikethrough_s </i>
            </button>
            <button class="unsplash-image toolbar-option">
                <i class="material-icons"> add_photo_alternate </i>
            </button>
            <button class="ql-header toolbar-option" value="1" type="button">
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="#000000" d="M3,4H5V10H9V4H11V18H9V12H5V18H3V4M14,18V16H16V6.31L13.5,7.75V5.44L16,4H18V16H20V18H14Z" />
                </svg>
            </button>
            <button class="ql-header toolbar-option" value="2" type="button">
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="#000000" d="M3,4H5V10H9V4H11V18H9V12H5V18H3V4M21,18H15A2,2 0 0,1 13,16C13,15.47 13.2,15 13.54,14.64L18.41,9.41C18.78,9.05 19,8.55 19,8A2,2 0 0,0 17,6A2,2 0 0,0 15,8H13A4,4 0 0,1 17,4A4,4 0 0,1 21,8C21,9.1 20.55,10.1 19.83,10.83L15,16H21V18Z" />
                </svg>
            </button>
            
            <span class="save"></span>
        </div>

        <div id="editor">
        </div>
    </div>
</div>

<div class="image-wrapper">
    <div class="image-close">
        Cancel
    </div>

    <div class="image-content">
        <div class="image-search">
            <form id="unsplash-search">
                <input class="image-search-input" placeholder="Search for images...">
            </form>
        </div>
        <div class="image-results">
            
        </div>
    </div>
</div>

<%= javascript_include_tag 'write' %>
<%= javascript_include_tag 'new' %>

app/views/articles/show.html.erb
<%= render "partials/navbar" %>

<div class="wrapper read">
    <div class="author-wrapper read-item">
        <img src="<%= Identicon.data_url_for @article.user.email %>" alt="" />
        <div class="author-details">
            <%= @article.user.email %>
        </div>
    </div>

    

    <div id="content" class="read-item">
    </div>

    <ul>
        <% if current_user %>
            <%= form_with model: [@article, Comment.new], class: "top" do |f| %>
                <%= f.text_area :content, placeholder: "Add a Reply", class: "main-comment" %>
                <div class="bar">
                    <%= f.submit "Reply",  class: "form-btn" %>
                </div>
            <% end %>
        <% end %>

        <%= render partial: "/partials/comment", collection: @article.comments, as: :comment, 
        locals: {author: @article.user.username } %>
    </ul>
</div>

<script>
    var content = <%= raw @article.content %>
</script>

<%= javascript_include_tag 'show' %>

app/views/home/index.html.erb
<%= render "partials/navbar" %>

<div class="wrapper view">
    
    <% if @intro %>
        <div class="intro-article">
            <div class="intro-content">
                <div class="author-wrapper">
                    <img src="<%= Identicon.data_url_for @intro.user.email %>" alt="" />
                    <div class="author-details">
                        <%= @intro.user.email %>
                    </div>
                </div>
                <h2 class="intro-title"><%= @intro.title %></h2>
                <h3 class="intro-subtitle"><%= @intro.subtitle %></h3>
                <h4 class="route" style="color: green;" data-path="/articles/<%= @intro.id %>">Read More</h4>
            </div>
            <div class="intro-img">
                <img src="<%= @intro.display_image %>" alt="" />
            </div>

        </div>
    <% end %>

    <% @articles.each do |article| %>
        <div class="small-article-home route" data-path="/articles/<%= article.id %>">
                <img class="small-img" src="<%= article.display_image %>" alt="" />
                <div class="small-content">
                    <h3 class="small-title"><%= article.title %></h1>
                    <h4 class="small-subtitle"><%= article.subtitle[0..60].gsub(/\s\w+\s*$/, ' ...') %></h4>
                    <div class="author-wrapper">
                        <img src="<%= Identicon.data_url_for article.user.email %>" alt="" />
                        <div class="author-details">
                            <%= article.user.email %>
                        </div>
                    </div>
                </div>
        </div>
    <% end %>
</div>

app/views/home/search.html.erb
<%= render "partials/navbar" %>

<div class="wrapper view">
    
    <div class="search-wrapper">
        <form id="search">
            <input id="q" type="text" placeholder="search..." autocomplete="off">
        </form>
    </div>
    

    <div class="results">
        <% @articles.each do |article| %>
            <div class="small-article-home route" data-path="/articles/<%= article.id %>">
                    <img class="small-img" src="<%= article.display_image %>" alt="" />
                    <div class="small-content">
                        <h3 class="small-title"><%= article.title %></h1>
                        <h4 class="small-subtitle"><%= article.subtitle[0..60].gsub(/\s\w+\s*$/, ' ...') %></h4>
                        <div class="author-wrapper">
                            <img src="<%= Identicon.data_url_for article.user.email %>" alt="" />
                            <div class="author-details">
                                <%= article.user.email %>
                            </div>
                        </div>
                    </div>
            </div>
        <% end %>
    </div>

    
</div>

<script>

    $("form#search").submit(function(e){
        e.preventDefault();

        $(".results").empty();

        var q = $("input#q").val()

        window.location = '/search?q='+ q

    })

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Writr</title>
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script>
        toastr.options = {
            "positionClass": "toast-bottom-left",
        }
    </script>
    <%= custom_flash %>
  </body>
</html>

app/views/partials/_comment.html.erb
<li>
  <div class="comment-wrapper">
      <img src="<%= Identicon.data_url_for comment.user.email %>" alt="" />
      <div class="content">
        <div class="byline">
          <b ><%= comment.user.username %></b> 
          <span style="color: #9F9F9F;"> <%= distance_of_time_in_words(comment.updated_at, Time.now) %> ago </span>
        </div>
        <div class="comment-body" data-id="<%= comment.id %>">
          <%= simple_format comment.content %>
        </div>
        <div class="comment-edit" data-id="<%= comment.id %>">
          <%= form_with model: comment, url: comment_path(comment), method: "patch" do |f| %>
            <%= f.text_area :content, placeholder: "Edit comment...", class: "main-comment", value: comment.content %>
              <div class="bar">
                  <button class="cancel form-btn" data-id="<%= comment.id %>">Cancel</button>
                  <%= f.submit "Reply",  class: "form-btn" %>
                  
              </div>
          <% end %>
        </div>
        <div class="actions">
          <div class="action under" data-type="reply" data-id="<%= comment.id %>">
            Reply
          </div>
          <% if current_user && current_user.username == author %>
            <div class="action under" data-type="edit" data-id="<%= comment.id %>">
              Edit
            </div>
            <div class="action under" data-type="delete" data-id="<%= comment.id %>">
              Delete
            </div>
          <% end %>
        </div>

         <div class="reply" data-id="<%= comment.id %>">
          <%= form_with model: [comment, Comment.new] do |f| %>
              <%= f.text_area :content, placeholder: "Add a Reply", class: "main-comment" %>
              <div class="bar">
                  <%= f.submit "Reply",  class: "form-btn" %>
              </div>
          <% end %>
        <div>

      </div>
  </div>


  <ul>
      <%= render partial: "/partials/comment", collection: comment.comments, as: :comment, locals: {author: author} %>
  </ul>

</li>

app/views/partials/_navbar.html.erb
<div class="navbar-wrapper wrapper">
    <div class="navbar">
        <div class="logo-wrapper route" data-path="/">
            <span class="logo">Writr</span>
            <span class="logo-mobile">W</span>
        </div>
         
        <div class="link-wrapper">
            <% if @publishable %>
                <div class="btn green publish">
                    Publish
                </div>
            <% end %>

            <%= image_tag("search.svg", :alt => "search", :class => "link route", :data => { :path => "/search"} ) %>
            <% if user_signed_in? %>
                <%= image_tag("bell.svg", :alt => "notif", :class => "link route", :data => { :path => "/notifications"} ) %>
                <div class="new btn link route" data-path="/articles/new">
                    New
                </div>

                <div class="dropdown">
                    <div class="avatar">
                         <img src="<%= Identicon.data_url_for current_user.email %>" alt="" />
                    </div>
                    <div class="dropdown-content-wrapper">
                    <div class="dropdown-content">
                        <div class="section-profile">
                                <div class="profile-avatar">
                                    <img src="<%= Identicon.data_url_for current_user.email %>" alt="" />
                                </div>
                            <div class="profile-name">
                                <p>
                                    Name
                                </p>
                                <p>
                                    @<%= current_user.username %>
                                </p>
                            </div>
                        </div>
                        <div class="routes">
                        <div class="divide"></div>
                        <p class="logout route hover" style="color: #029e74;">Logout</p>
                        <div class="divide"></div>
                        <p class="route hover" data-path="/articles/new">New Article</p>
                        <p class="route hover" data-path="/me/articles">Articles</p>
                        <p class="route hover" data-path="/me/stats">Stats</p>
                        <div class="divide"></div>
                        <p class="hover">Getting Stated</p>
                        <div class="divide"></div>
                        <p class="route hover" data-path="/@<%= current_user.username %>">Profile</p>
                        <p class="hover">Settings</p>
                        <p class="hover">Help</p>
                        </div>
                    </div>
                    </div>
                </div>
            <% else %>
                <div class="green btn link route" data-path="/login">
                    Login
                </div>
                <div class="green border btn link route" data-path="/register">
                    Sign up
                </div>
            <% end %>

        </div>
    </div>
</div>

<div class="publish-wrapper">
    <div class="publish-top">
        <h1>
        Publish Article
        </h1>
        <div class="publish-close btn">
        Cancel
    </div>
    </div>
    

    <div class="publish-content">
        <div class="col">
            <div class="publish-image" data-default="<%= image_path('writr3.svg') %>">
            </div>

            <h4>Preview Image</h4>
            
        </div>
        <div class="col meta">
            <p>
                Add tags to make it easier to find you article
            </p>
            <div class="input-group">
                <input name='tags' class="input-border" contenteditable="true" placeholder="Add tags..."/>
                <h4>HINT: Press enter after typing to add tag</h4>
                <div class="input publish-title" contenteditable="true" placeholder="Preview title..."></div>

                <div class="input publish-subtitle" contenteditable="true" placeholder="Preview subtitle..."></div>
            </div>

            <div class="btn solid publish-submit">
                Publish
            </div>
        </div>

    </div>
</div>

app/views/users/articles.html.erb
<%= render "partials/navbar" %>

<div class="wrapper">
    <div class="header">
        <h1>Your Articles</h1>
        <div class="btns">
            <div class="btn new h route" data-path="/articles/new">
                Write Article
            </div>
            <div class="btn border green h">
                Import Article
            </div>
        </div>
    </div>
    <div class="articles">
        <div class="divide" style="height: 2px;"></div>
        <% @articles.each do |article| %>
            <div class="article">
                <div class="info">
                    <h2 class="route" style="display: flex; align-items: center;" 
                        data-path="<%= article.draft ? "/articles/#{article.id}/edit" : "/articles/#{article.id}" %>"><%= article.title %>
                    <% if article.draft %>
                        <span class="small">DRAFT</span>
                    <% end %>
                    </h2>
                    <h4>Last Updated: <%= article.updated_at.strftime("%m/%d/%Y") %></h4>
                </div>

                <%= image_tag("ellipsis.svg", :alt => "more", :class => "more", :draggable => "false", :data => { :id => article.id}) %>
                <div class="options" data-id="<%= article.id %>">
                    <div class="option edit" data-id="<%= article.id %>">
                        Edit
                    </div>
                    <% if article.draft %>
                        <div class="option">
                            Publish
                        </div>
                    <% end %>
                    <div class="option red delete" data-id="<%= article.id %>">
                        Delete
                    </div>
                </div>
            </div>
            <div class="divide" style="height: 2px;"></div>
        <% end %>
    </div>
</div>

<%= javascript_include_tag 'articles' %>

app/views/users/profile.html.erb
<%= render "partials/navbar" %>

<div>
<% if @user %>

    <div class="wrapper view">

        <div class="banner">
             <div class="banner-profile">
                <img class="avatar" src="<%= Identicon.data_url_for @user.email %>" alt="" />
                <h1><%= @user.username %></h1>
             </div>
             <div>
                <%= @user.articles.length %> Articles
             </div>
        </div>

        <div>
        <% @user.articles.each do |article| %>
            <div class="small-article route" data-path="/articles/<%= article.id %>">
                    <img class="small-img" src="<%= article.display_image %>" alt="" />
                    <div class="small-content">
                        <h3 class="small-title"><%= article.title %></h1>
                        <h4 class="small-subtitle"><%= article.subtitle[0..60].gsub(/\s\w+\s*$/, ' ...') %></h4>
                    </div>
            </div>
        <% end %>
        </div>

    </div>

<% else %>

 NO SUCH USER :)
 
<% end %>

</div>